language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: UMe84F7f9T1pezGfYvqemKT628rSduOyMKDdhc2mGyJG7f8+2yZWLpDUdKO4fGzshC7GvJ9kPj0LtrxQ0tXZlCxoskxNf3rYhUlFv+xqowndaj4DNdKOvC0HLgHmxitWo8/vyJmM7b9EMJWY9/BGJhqy/ckc63hd5dOHHRj2pJxSbnkbjlhLebJ7+8rmSgyzxFYlW52A+4aV33Kv3F185FUVLHWMYhrlfmUg+u7VcY58jONsXRtvuNCGEbk/uI2k7C6wDh/6+rRFXXpyNzDwUvEbKCQtSJcngTC4yk979KjzZit0fwLBi5628jKg1QrDQDeF9Za13OC1jT380yv7eCBpaQoiwgcyFnLiEV4DZVw6WAp5TmtJX6uP7gM5cCuPFPy/i3rma9mHBZH+B3eOqt1IIjYf2XUnumMGgEBkpu9+Q6ROWuldx8Zfa4s0CXtOk7OzMG4HewX1WbK0+DLda4gF7oMVGPq401X4Z6UJHhDQd2V08HbzsamsQ58Q6ub7UvYssDyhq7ZPKdQhCcXo1niLsPN/REfehRvZOLD88M7FMsr1gEG0PxYp0bJxvn2fn+11B3gYIlYZf0INKB5Qkm+7Mu5va3iupex4wGNE3fapXBp3mXDJ6e/qzYhcgIlEESVg9qHATP/Vc3NZfXFq8CP309RjkAtxHu2bE/ZS4Rw=
  - secure: jYQ0y7bxmoO8eUJla36y1zrhtnxi0guSD4ufRQGnYmAlp7sWYeCBQj4ACXnIaTOwAhd2EpFUUp8BZ0z7W5sDUgOdYqAQe1eTe17kc2xJmDHMkW3INRYAW7LVgZTDmFLAmh5pXcdv0roGqB3KoU9PauhO8Q1h6IHwwbRslPngX2A2MYQLpobugmi0AxUff1C6bSP3rdO0GHbaAN6sYMtPzZRTeiRLaBCh3gbQhYVLFmfqVdYulHAS1TqaOGUpMEosfC+FIw/14b1u+pyWQHA5BSBrDDmqnHjcQZtugQNJP2Epw8UW1aVM1HwlU5fh3/Ru/LZ/+bDc/Xg26C+OKJzF5Loo8owdlFcPjh7/hnamARz8jhB2jCJzwpTtBeTkX6O9xVDoPcBnNypaf3Ck8glZ0xg9AbnpOwmy7KYbKffDe6uRq6whJEQOvgmdTYlFXWS1wY0IS2J2pPw9QaHmhM+eQNxS1mrL59CPsP9y+b58mNRPLMscE3RYn5un5xlRYQKbT1JUHh0eFmVlAciEl5U5t2FGccPwSUyPN9pM2yf/1jmyNq16sR8XCvMgzHXI2Hev8UumEq2qthQfZ6WfXQDSfJhgPCsCZq89IhxmzwOLACk7Tk/Bw4ryrSfldfGxpozuJmppQGRatPwaJToHKLg1CcoQ/6d5wxpViS68X1HrZWY=
  - secure: GqeZ2iuWfSeIDCfrSNSW6JxZo1BBs7qENPOCWLgDxCkGTv34vu692afDwRLns24TLfnZLn1WZSmR6wDhdmlAXnSxaYyyyRc43hkEb6u2dmXiwkrvnKEMQhJOjxyIbf5UVsuRmZQaiBfPs6qXM8NFAVtRdDDMFFAcp3tnVnkiMx2yjYbBqkhAhTJi2YQaBSKbqQaxOerDHKXKdSm/hxHEaoWwH6IDal9yL2mTDdRclDknmGSMBe16o9suOdUlrJmpOPDcNLH7ZLsYpS+CnCRsIiyv45SCOlV1w1lgkjuBNeh213hsqHqzsLNmqGaOQxCxFxFjKUjJaS9GiYNZidkHdZyROI6aP3vkeTRpLjavCaZZR2BdL3hVIaKtmVMMbB5ONcAmtVsxj/Z+YAatWi5UB1N3lrc+MQADZU7Oa9uvZeGg38T5ppMwZuH+D+B9B4J3XuiCPQvBwOO6zRF2/QXuc2c4s2Xk6+eXr9b7c3GR4K3abztpFyrPQK1OtfGXx2j92+6fLjtwioHLl9CaSanm+9+zBT+zv08HFWbP/PhIdIulOhM5akx1DBVzNaEbKb8uAI4l/Quf7AZDJcCxZRM0/wgMgV2wvY9OIWj99TpsStVIKv/rvBflv0BWGk+tv49eiJoZgo/3BVKYi6fON7VEWovzBMNfgQXweeMESF+TIiY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client==0.12.5
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn build:browser
deploy:
- provider: script
  repo: cozy/cozy-store
  skip-cleanup: true
  script: yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  repo: cozy/cozy-store
  skip-cleanup: true
  script: yarn deploy && yarn cozyPublish
  on:
    tags: true
